### ISSUE TITLE
FeedMe completely stopped working

### ISSUE THREAD

**Issue by KarlBishop** [craftcms/feed-me#1204]
We have a nightly JSON feed that stopped working.

I put the feed content through a validator and it is valid JSON.

When I click **Run Feed** I get a message saying "Feed Processing Started" but nothing happens. The usual Queue Job is not created. There are no errors shown in the log.

When I try editing the feed I hit a 500 error:
- I can click "Save and Continue" on the first page, where you enter Name and Feed URL...
- I can click "Save and Continue" on the second page, where you select **Primary Element**...
- But then I see **Internal Server Error**

When I try editing other feeds that have been run successfully in the past they all hit a 500 error at the same point. These other feeds are static XML and JSON files in @storage that have been untouched since they were successfully imported, so looks like the problem is with FeedMe or Craft itself rather than any individual feed content(?)

When the 500 errors occur the log shows **web_php_errors** - something to do with **strtolower()**:

````
web_php_error  2022-11-17T01:11:42Z 2022-11-17 02:11:42 [-][1][4328j8cf432jc09432][error][yii\base\ErrorException:2] yii\base\ErrorException: strtolower() expects parameter 1 to be string, object given in /srv/app/mywebsite/htdocs/vendor/craftcms/cms/src/web/twig/Extension.php:493
web_php_error  2022-11-17T01:11:42Z Stack trace:
web_php_error  2022-11-17T01:11:42Z #1 [internal function]: craft\web\ErrorHandler->handleError(2, 'strtolower() ex...', '/srv/app/mywebs...', 493, Array)
web_php_error  2022-11-17T01:11:42Z #0 /srv/app/mywebsite/htdocs/vendor/craftcms/cms/src/web/ErrorHandler.php(87): yii\base\ErrorHandler->handleError(2, 'strtolower() ex...', '/srv/app/mywebs...', 493)
web_php_error  2022-11-17T01:11:42Z #2 /srv/app/mywebsite/htdocs/vendor/craftcms/cms/src/web/twig/Extension.php(493): strtolower(Object(Closure))
web_php_error  2022-11-17T01:11:42Z #3 /srv/app/mywebsite/htdocs/storage/runtime/compiled_templates/d2/d25ffcde3dc6fcfb29e4f0fd8d79d605da85b7c1abd3555fa0f97443c527d19d.php(158): craft\web\twig\Extension->sortFilter(Object(craft\web\twig\Environment), Array, Object(Closure))
web_php_error  2022-11-17T01:11:42Z #4 /srv/app/mywebsite/htdocs/vendor/twig/twig/src/Template.php(182): __TwigTemplate_308b8b3280ee164ec4cd3fce500a2615c129b9f9b3fef926e1b504fa0935e614->block_content(Array, Array)
web_php_error  2022-11-17T01:11:42Z #5 /srv/app/mywebsite/htdocs/storage/runtime/compiled_templates/6c/6cdae0751ee2cf6d80a5a7b1781786cb2e17060c8d315b980a19d6a1b51ac7de.php(547): Twig\Template->displayBlock('content', Array, Array)
web_php_error  2022-11-17T01:11:42Z #6 /srv/app/mywebsite/htdocs/vendor/twig/twig/src/Template.php(182): __TwigTemplate_e7c4dfa42977a49d574796d445791bded2b039a4cd26220df303717446184d93->block_main(Array, Array)
web_php_error  2022-11-17T01:11:42Z #7 /srv/app/mywebsite/htdocs/storage/runtime/compiled_templates/6c/6cdae0751ee2cf6d80a5a7b1781786cb2e17060c8d315b980a19d6a1b51ac7de.php(358): Twig\Template->displayBlock('main', Array, Array)
web_php_error  2022-11-17T01:11:42Z #8 /srv/app/mywebsite/htdocs/vendor/twig/twig/src/Template.php(182): __TwigTemplate_e7c4dfa42977a49d574796d445791bded2b039a4cd26220df303717446184d93->block_body(Array, Array)
web_php_error  2022-11-17T01:11:42Z #9 /srv/app/mywebsite/htdocs/storage/runtime/compiled_templates/8c/8c4b1d61b45fe8e1437dd549ecdcc4a9f08bad0c684868328da516f1dd150f85.php(91): Twig\Template->displayBlock('body', Array, Array)
web_php_error  2022-11-17T01:11:42Z #10 /srv/app/mywebsite/htdocs/vendor/twig/twig/src/Template.php(405): __TwigTemplate_8811fa3be63c59dcf01f407a58e0f04222af93cafff297420c7fc85e5959578a->doDisplay(Array, Array)
web_php_error  2022-11-17T01:11:42Z #11 /srv/app/mywebsite/htdocs/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
web_php_error  2022-11-17T01:11:42Z #12 /srv/app/mywebsite/htdocs/storage/runtime/compiled_templates/7c/7c45a214b5e89f96a4364c37caad86de4e3f3a25dc502fa1ba40e73f866431b0.php(56): Twig\Template->display(Array, Array)
web_php_error  2022-11-17T01:11:42Z #13 /srv/app/mywebsite/htdocs/vendor/twig/twig/src/Template.php(405): __TwigTemplate_79f084a6b3efaf13e888fe9830a5e08ecf5207e5e0e71320179ff8e603e9f3fe->doDisplay(Array, Array)
web_php_error  2022-11-17T01:11:42Z #14 /srv/app/mywebsite/htdocs/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
web_php_error  2022-11-17T01:11:42Z #15 /srv/app/mywebsite/htdocs/storage/runtime/compiled_templates/6c/6cdae0751ee2cf6d80a5a7b1781786cb2e17060c8d315b980a19d6a1b51ac7de.php(172): Twig\Template->display(Array, Array)
web_php_error  2022-11-17T01:11:42Z
web_php_error  2022-11-17T01:11:42Z $_POST = []
web_php_error  2022-11-17T01:11:42Z $_FILES = []
web_php_error  2022-11-17T01:11:42Z $_COOKIE = [
web_php_error  2022-11-17T01:11:42Z 'form_posted_2' => '4832980324'
web_php_error  2022-11-17T01:11:42Z '8342098034 n2034289vn38204nv_username' => 'e540de7b9421d356d28c4f3e4eb7bf4335e5fe5afd59f174fa98d9f9b23fda5da:2:{i:0;s:41:\"8342098034 n2034289vn38204nv_username\";i:1;s:18:\"Karl\";}'
web_php_error  2022-11-17T01:11:42Z 'form_posted_1' => '3742873492'
web_php_error  2022-11-17T01:11:42Z '_pk_id_1_d166' => '4832098324023.3427984327.'
web_php_error  2022-11-17T01:11:42Z ]
web_php_error  2022-11-17T01:11:42Z
apache_access  122.58.41.250 - - [17/Nov/2022:01:11:39 +0000] "GET /admin/feed-me/feeds/map/46?p=admin/feed-me/feeds/map/46 HTTP/1.1" 500 39974 "https://www.mywebsite.com/admin/feed-me/feeds/element/46" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36"
````

When I try to edit a feed locally, I see this screen:

![image](https://user-images.githubusercontent.com/2892126/202336263-eaf27016-b76c-4042-b47f-8cf5365662d1.png)

I'm not sure if this is an issue with FeedMe or Craft itself, so have also raised it on the `cms` repo here:
[[3.x]: strtolower() in craftcms/cms/src/web/twig/Extension.php is preventing FeedMe from running #12334](https://github.com/craftcms/cms/issues/12334)

### Additional info

- Craft version: 3.7.57 and now 3.7.60
- PHP version: 7.4.28
- Database driver & version: MySQL 8.0.28
- Plugins & versions:
Asset Usage	2.3.1
Blitz	3.12.6
Bulk Edit	2.0.6
Cloner	1.2.2
Control Panel Nav	3.0.17
Cookiebot	1.0.9
Copy	1.2.4
Dashboard Begone	1.0.1
Element API	2.8.6.1
Embedded Assets	2.11.3
Feed Me	4.5.3
fortrabbit Object Storage Volume	2.1.0
Freeform	3.13.21
Image Resizer	2.1.1
Minify	1.2.11
Patrol	4.0.2
Redactor	2.10.10
Relax	1.0.1
Retcon	2.6.0
Sentry Logger	1.3.1
SEOmatic	3.4.42
Sherlock	3.1.4
Super Table	2.7.3

**Comment by chrisrowe** [comment]
Same here. PHP 8.1
`strtolower(): Argument #1 ($string) must be of type string, Closure given`

**Comment by brandonkelly** [comment]
Sorry about this! Craft 3.7.61 and 4.3.3 are out with a fix for this.
