### ISSUE TITLE
Undefined property: stdClass::$Logo (airtable Feed / Import)

### ISSUE THREAD

**Issue by maxstrebel** [craftcms/feed-me#1411]
### Description

I have an Airtable importer that throws `Undefined property: stdClass::$Logo`. When devMode is deactived I can run the import. But in devMode, the error stops me from importing.

### Steps to reproduce

1. Be in devMode
2. Import an Airtable Feed that has a Attachment Field (called Logo, I guess)
3. Save & go to next step (selection of the root element)
4. See error message (Stack trace below)

### Additional info

- Craft version: Craft Pro 4.7.2.1
- PHP version: 8.1.21
- Database driver & version: MariaDB 10.4.30
- Plugins & versions:
  - Feed-me 5.3.0

<img width="424" alt="image" src="https://github.com/craftcms/feed-me/assets/910594/c36b384e-16a0-4f48-8eb8-f25bbaa92f0a">

```

{
	"records": [
		{
			"id":"XXX",
			"createdTime":"xxxx-xx-xxTxx:xx:xx.xxxx",
			"fields": {
				"name":"XXX",
				"website":"http://XXX",
				"city":"xxx",
				"description":"XXX",
				"logo": [
					{
						"id":"xxx",
						"width":112,
						"height":28,
						"url":"https://xxx",
						"filename":"xxx.png",
						"size":1621,
						"type":"image/png",
						"thumbnails": {
							"small": {
								"url":"https://xxx",
								"width":112,
								"height":28
							},
							"large": {
								"url":"https://xxx",
								"width":112,
								"height":28
							},
							"full": {
								"url":"https://xxx",
								"width":3000,
								"height":3000
							}
						}
					}
				],
				"country":"xxx",
				...
			}
		},
		{
			...
		}
	]
}
	
```

```
yii\base\ErrorException: Undefined property: stdClass::$Logo in /var/www/html/modules/airtableimport/Module.php:37
Stack trace:
#0 /var/www/html/vendor/craftcms/cms/src/web/ErrorHandler.php(79): yii\base\ErrorHandler->handleError(2, 'Undefined prope...', '/var/www/html/m...', 37)
#1 /var/www/html/modules/airtableimport/Module.php(37): craft\web\ErrorHandler->handleError(2, 'Undefined prope...', '/var/www/html/m...', 37)
#2 [internal function]: modules\airtableimport\Module->modules\airtableimport\{closure}(Object(craft\feedme\events\FeedDataEvent))
#3 /var/www/html/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Object(Closure), Object(craft\feedme\events\FeedDataEvent))
#4 /var/www/html/vendor/craftcms/feed-me/src/services/DataTypes.php(492): yii\base\Event::trigger('craft\\feedme\\se...', 'onAfterFetchFee...', Object(craft\feedme\events\FeedDataEvent))
#5 /var/www/html/vendor/craftcms/feed-me/src/services/DataTypes.php(226): craft\feedme\services\DataTypes->_triggerEventAfterFetchFeed(Array)
#6 /var/www/html/vendor/craftcms/feed-me/src/datatypes/Json.php(34): craft\feedme\services\DataTypes->getRawData('https://api.air...', 8)
#7 /var/www/html/vendor/craftcms/feed-me/src/services/DataTypes.php(237): craft\feedme\datatypes\Json->getFeed('https://api.air...', Object(craft\feedme\models\FeedModel), false)
#8 /var/www/html/vendor/craftcms/feed-me/src/models/FeedModel.php(207): craft\feedme\services\DataTypes->getFeedData(Object(craft\feedme\models\FeedModel), false)
#9 /var/www/html/vendor/craftcms/feed-me/src/controllers/FeedsController.php(88): craft\feedme\models\FeedModel->getFeedNodes()
#10 [internal function]: craft\feedme\controllers\FeedsController->actionElementFeed('8', NULL)
#11 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#12 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#13 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('element-feed', Array)
#14 /var/www/html/vendor/craftcms/cms/src/web/Application.php(305): yii\base\Module->runAction('feed-me/feeds/e...', Array)
#15 /var/www/html/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('feed-me/feeds/e...', Array)
#16 /var/www/html/vendor/craftcms/cms/src/web/Application.php(290): yii\web\Application->handleRequest(Object(craft\web\Request))
#17 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#18 /var/www/html/web/index.php(22): yii\base\Application->run()
#19 {main}
```

**Comment by maxstrebel** [comment]
Sorry, was a custom module I did not know about.
