### ISSUE TITLE
PHP Exception thrown when using feed-me/feeds/run CLI without ID

### ISSUE THREAD

**Issue by jamesmacwhite** [craftcms/feed-me#528]
### Description

Not a bug, given you wouldn't use the CLI command without any ID, but if you try and run `./craft feed-me/feeds/run` without any Feed ID specified, you get a PHP exception. Potentially would it be nicer to gracefully error and check if an ID is specified before executing.

```
/app $ ./craft feed-me/feeds/run
Feed processing started for Feed ID feeds
PHP Notice 'yii\base\ErrorException' with message 'Trying to get property of non-object'

in /app/vendor/craftcms/feed-me/src/queue/jobs/FeedImport.php:96

Stack trace:
#0 /app/vendor/craftcms/cms/src/queue/Queue.php(143): craft\feedme\queue\jobs\FeedImport->getDescription()
#1 /app/vendor/craftcms/feed-me/src/console/controllers/FeedsController.php(43): craft\queue\Queue->push()
#2 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): craft\feedme\console\controllers\FeedsController->actionRun()
#3 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): ::call_user_func_array:{/app/vendor/yiisoft/yii2/base/InlineAction.php:57}()
#4 /app/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams()
#5 /app/vendor/yiisoft/yii2/console/Controller.php(148): craft\feedme\console\controllers\FeedsController->runAction()
#6 /app/vendor/yiisoft/yii2/base/Module.php(528): craft\feedme\console\controllers\FeedsController->runAction()
#7 /app/vendor/yiisoft/yii2/console/Application.php(180): craft\console\Application->runAction()
#8 /app/vendor/craftcms/cms/src/console/Application.php(93): craft\console\Application->runAction()
#9 /app/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction()
#10 /app/vendor/yiisoft/yii2/base/Application.php(386): craft\console\Application->handleRequest()
#11 /app/craft(26): craft\console\Application->run()
#12 {main}
```

**Comment by angrybrad** [comment]
Same issue and resolved in https://github.com/craftcms/feed-me/issues/754
