### ISSUE TITLE
Unknown property 'type' error during field assignment

### ISSUE THREAD

**Issue by matthisamoto** [craftcms/feed-me#609]
### Description

When trying to select and assign the fields for columns in a CSV feed, I am receiving this error:

`Getting unknown property: craft\redactor\Field::type in /data/27/5/89/50/5415213/user/6483213/htdocs/vendor/yiisoft/yii2/base/Component.php:15`

This **only** occurs on a remote server and it's not the best host, currently on PHP v7.0.2 and I am working to get this upgraded. I was hoping to see if this was the cause of my problem but it's taking a while to get a response from the host. On my local machine the plugin works fine on PHP v7.2.21. The vendor files are all exactly the same, I have tried reinstalling the CMS and plugins to no avail.

### Steps to reproduce

1. Create a new feed
2. Complete the steps up to selecting the field relationships
3. Continue to fields and receive error

### Additional info

- Plugin version: 
- Craft version: 3.3.4.1
- PHP version: 7.0.2

#### System Report

PHP version	7.0.2
OS version	Linux 4.7.10-hardened
Database driver & version	MySQL 5.6.44
Image driver & version	Imagick 3.4.0RC2 (ImageMagick 6.9.0-3)
Craft edition & version	Craft Pro 3.3.4.1
Yii version	2.0.21
Twig version	2.11.3
Guzzle version	6.3.3
Imagine version	1.2.3-dev
Plugins
Breadcrumb	1.0.4
Cloner	1.0.3
Control Panel CSS	2.2.0
Control Panel Nav	2.0.9
Expanded Singles	1.0.7
Feed Me	4.1.2
Field Manager	2.1.0
Imager	v2.3.0
Image Resizer	2.0.6
Many to Many Field Type	1.0.2.2
Redactor	2.4.0
SEO	3.6.2
Smith	1.0.0
Super Table	2.3.0
Typed link field	1.0.19
Typogrify	1.1.18

#### Full Stack Trace

yii\base\UnknownPropertyException: Getting unknown property: craft\redactor\Field::type in /data/27/5/89/50/5415213/user/6483213/htdocs/vendor/yiisoft/yii2/base/Component.php:154
Stack trace:
#0 /data/27/5/89/50/5415213/user/6483213/htdocs/vendor/yiisoft/yii2/base/Model.php(1026): yii\base\Component->__get('type')
#1 /data/27/5/89/50/5415213/user/6483213/htdocs/vendor/craftcms/feed-me/src/web/twig/variables/FeedMeVariable.php(257): yii\base\Model->offsetGet('type')
#2 /data/27/5/89/50/5415213/user/6483213/htdocs/vendor/twig/twig/src/Extension/CoreExtension.php(1485): craft\feedme\web\twig\variables\FeedMeVariable->fieldCanBeUniqueId(Object(craft\redactor\Field))
#3 /data/27/5/89/50/5415213/user/6483213/htdocs/vendor/craftcms/cms/src/helpers/Template.php(105): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\feedme\web\twig\variables\FeedMeVariable), 'fieldCanBeUniqu...', Array, 'method', false, false)
#4 /data/27/5/89/50/5415213/user/6483213/htdocs/storage/runtime/compiled_templates/91/91eeda940a2b12e7bf3b708e80f7784159dc2011a3a27344c55dffdc5adc2637.php(103): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\feedme\web\twig\variables\FeedMeVariable), 'fieldCanBeUniqu...', Array, 'method')
#5 /data/27/5/89/50/5415213/user/6483213/htdocs/vendor/twig/twig/src/Template.php(184): __TwigTemplate_675ebe7f71b85b2a0d9356f26eaf33354e5bfb34e412b4893d2b66e60a326762->block_extraSettings(Array, Array)
#6 /data/27/5/89/50/5415213/user/6483213/htdocs/storage/runtime/compiled_templates/c8/c8ad472358eb26b42d9c1e053389f0634a6ad2d4b8ae1b3b053faed2a49c6af3.php(237): Twig\Template->displayBlock('extraSettings', Array, Array)
#7 /data/27/5/89/50/5415213/user/6483213/htdocs/vendor/twig/twig/src/Template.php(407): __TwigTemplate_640787d25237d2c773ec72e03e58e35a891e0b6af6d25d28a5f7cd8b07c9e504->doDisplay(Array, Array)
#8 /data/27/5/89/50/5415213/user/6483213/htdocs/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#9 /data/27/5/89/50/5415213/user/6483213/htdocs/storage/runtime/compiled_templates/91/91eeda940a2b12e7bf3b708e80f7784159dc2011a3a27344c55dffdc5adc2637.php(73): Twig\Template->display(Array, Array)
#10 /data/27/5/89/50/5415213/user/6483213/htdocs/vendor/twig/twig/src/Template.php(407): __TwigTemplate_675ebe7f71b85b2a0d9356f26eaf33354e5bfb34e412b4893d2b66e60a326762->doDisplay(Array, Array)
#11 /data/27/5/89/50/5415213/user/6483213/htdocs/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#12 /data/27/5/89/50/5415213/user/6483213/htdocs/storage/runtime/compiled_templates/5f/5f09b59aa9eaa806a9226a75ff62f59b1ffc09a7b9ee77ae177ac37aade714c8.php(156): Twig\Template->display(Array)
#13 /data/27/5/89/50/5415213/user/6483213/htdocs/vendor/twig/twig/src/Template.php(407): __TwigTemplate_c0ba60879a0939ed317bf3e999699f250a8269ef07399cb14a93ef3fcd200cc6->doDisplay(Array, Array)
#14 /data/27/5/89/50/5415213/user/6483213/htdocs/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#15 /data/27/5/89/50/5415213/user/6483213/htdocs/storage/runtime/compiled_templates/62/6256557b5c6c8c5bdc39c3263a3cded5a3c4d11b89abf6ce00fee391cc6ae628.php(163): Twig\Template->display(Array)
#16 /data/27/5/89/50/5415213/user/6483213/htdocs/vendor/twig/twig/src/Template.php(184): __TwigTemplate_a66244cd9914ae19c1caf37bd3a3d5844004bb2e2c7f6fd7400eb1aaf603fecb->block_blockContent(Array, Array)
#17 /data/27/5/89/50/5415213/user/6483213/htdocs/storage/runtime/compiled_templates/85/8535e6d7ae0d8af2d6799b6c5a29bf2c2b6096e3e86faeae0d3ec40ab301893f.php(62): Twig\Template->displayBlock('blockContent', Array, Array)
#18 /data/27/5/89/50/5415213/user/6483213/htdocs/vendor/twig/twig/src/Template.php(407): __TwigTemplate_8e1726513e32a8491f8bfa8558e1eb164948f32488e948b6e7fc1a03e62cb7fa->doDisplay(Array, Array)
#19 /data/27/5/89/50/5415213/user/6483213/htdocs/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#20 /data/27/5/89/50/5415213/user/6483213/htdocs/storage/runtime/compiled_templates/62/6256557b5c6c8c5bdc39c3263a3cded5a3c4d11b89abf6ce00fee391cc6ae628.php(80): Twig\Template->display(Array, Array)
#21 /data/27/5/89/50/5415213/user/6483213/htdocs/vendor/twig/twig/src/Template.php(407): __TwigTemplate_a66244cd9914ae19c1caf37bd3a3d5844004bb2e2c7f6fd7400eb1aaf603fecb->doDisplay(Array, Array)
#22 /data/27/5/89/50/5415213/user/6483213/htdocs/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#23 /data/27/5/89/50/5415213/user/6483213/htdocs/vendor/twig/twig/src/Template.php(392): Twig\Template->display(Array)
#24 /data/27/5/89/50/5415213/user/6483213/htdocs/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#25 /data/27/5/89/50/5415213/user/6483213/htdocs/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#26 /data/27/5/89/50/5415213/user/6483213/htdocs/vendor/craftcms/cms/src/web/View.php(344): Twig\Environment->render('feed-me/feeds/_...', Array)
#27 /data/27/5/89/50/5415213/user/6483213/htdocs/vendor/craftcms/cms/src/web/View.php(393): craft\web\View->renderTemplate('feed-me/feeds/_...', Array)
#28 /data/27/5/89/50/5415213/user/6483213/htdocs/vendor/craftcms/cms/src/web/Controller.php(243): craft\web\View->renderPageTemplate('feed-me/feeds/_...', Array)
#29 /data/27/5/89/50/5415213/user/6483213/htdocs/vendor/craftcms/feed-me/src/controllers/FeedsController.php(84): craft\web\Controller->renderTemplate('feed-me/feeds/_...', Array)
#30 [internal function]: craft\feedme\controllers\FeedsController->actionMapFeed('3', NULL)
#31 /data/27/5/89/50/5415213/user/6483213/htdocs/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#32 /data/27/5/89/50/5415213/user/6483213/htdocs/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#33 /data/27/5/89/50/5415213/user/6483213/htdocs/vendor/craftcms/cms/src/web/Controller.php(187): yii\base\Controller->runAction('map-feed', Array)
#34 /data/27/5/89/50/5415213/user/6483213/htdocs/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('map-feed', Array)
#35 /data/27/5/89/50/5415213/user/6483213/htdocs/vendor/craftcms/cms/src/web/Application.php(299): yii\base\Module->runAction('feed-me/feeds/m...', Array)
#36 /data/27/5/89/50/5415213/user/6483213/htdocs/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('feed-me/feeds/m...', Array)
#37 /data/27/5/89/50/5415213/user/6483213/htdocs/vendor/craftcms/cms/src/web/Application.php(284): yii\web\Application->handleRequest(Object(craft\web\Request))
#38 /data/27/5/89/50/5415213/user/6483213/htdocs/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#39 /data/27/5/89/50/5415213/user/6483213/htdocs/web/index.php(21): yii\base\Application->run()
#40 {main}

**Comment by matthisamoto** [comment]
Ended up having to change hosts for a variety of reasons and now this does not occur.
